/*
 * Round-trip checks for apps/web/crypto.js.
 *
 *     node dev/crypto.test.mjs
 *
 * This is the test the build order puts before the form. A form that
 * silently produces undecryptable ciphertext is indistinguishable from a
 * working one until export day, and by then the data is gone - so the
 * proof that encrypt and decrypt agree has to exist before anything is
 * collected, not after.
 *
 * Node's WebCrypto is the same specification the browser implements, so
 * the real file runs here unmodified. It is loaded through a data: URL,
 * the way dev/worker.test.mjs loads the Worker: crypto.js is a classic
 * script that assigns to globalThis, this repository has no package.json,
 * and importing the real bytes is what makes this a test of what ships
 * rather than of a copy.
 *
 * Two kinds of check, and the second is the one worth having:
 *
 *   - a fresh keypair encrypts and decrypts, and the failures fail.
 *   - a ciphertext committed months ago still opens. Rows outlive the
 *     code that wrote them. Every other test here passes just as happily
 *     after a change that quietly alters the format - a new label, a
 *     different salt, a reordered header - and that change would leave
 *     the live database unreadable with no error anywhere. The fixture
 *     below is the only thing that notices.
 */
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const HERE = (p) => fileURLToPath(new URL(p, import.meta.url));

const src = await readFile(HERE("../apps/web/crypto.js"), "utf8");
await import("data:text/javascript," + encodeURIComponent(src));
const { encrypt, encryptTo, decrypt, importPrivateKey, importPublicKey } =
  globalThis.BinderCrypto;

/*
 * The test keypair. Throwaway, committed on purpose: it protects
 * nothing and opens nothing real. The key the portal actually uses was
 * generated by the keyholder on their own machine and has never been in
 * this repository - see DESIGN.md, "Key custody".
 */
const keyFile = JSON.parse(await readFile(HERE("test-key.json"), "utf8"));

/*
 * The second recipient of a version 2 row: throwaway in exactly the same
 * way, standing in for a member's own device key while `keyFile` stands
 * in for the keyholder. A real member key is generated inside the
 * member's browser and is non-extractable, so no file can hold one -
 * which is the property this stand-in cannot reproduce and the reason it
 * is named a stand-in rather than an example.
 */
const memberKeyFile =
  JSON.parse(await readFile(HERE("test-member-key.json"), "utf8"));

/*
 * A ciphertext written by version 1 of the format, against the key
 * above, and the record it must come back as. Kept in its own file
 * because crypto-browser-check.html reads the same one - the same
 * assertion made twice against two copies of the fixture would be two
 * things to keep in step, and the copy that drifted would be the one
 * still passing.
 *
 * Do not regenerate it to make a failing test pass. See dev/README.md.
 */
const FIXTURE = JSON.parse(await readFile(HERE("fixture.json"), "utf8"));

/*
 * The same thing for version 2, and it carries its own copy of the
 * record rather than borrowing FIXTURE's. Two frozen blobs need two
 * frozen records: the day somebody changes what a submission looks
 * like, a shared record would quietly redefine what these bytes are
 * being asserted to contain, and both fixtures would agree with each
 * other about the wrong answer.
 *
 * Generated once, against dev/test-key.json as the keyholder and
 * dev/test-member-key.json as the member, by the encryptTo in
 * apps/web/crypto.js. Its provenance line is inside the file. Do not
 * regenerate it to make a failing test pass - the same rule and the
 * same reason as version 1. See dev/README.md.
 */
const FIXTURE2 = JSON.parse(await readFile(HERE("fixture-v2.json"), "utf8"));

/* What server/worker.js will accept: standard base64, nothing else. */
const WORKER_BASE64 = /^[A-Za-z0-9+/]+={0,2}$/;

const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);

function bytesOf(base64) {
  const binary = atob(base64);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
  return out;
}

function base64Of(bytes) {
  let binary = "";
  for (const b of bytes) binary += String.fromCharCode(b);
  return btoa(binary);
}

/* Flip one bit at `at`, counting from the end when negative. */
function tamper(base64, at) {
  const bytes = bytesOf(base64);
  const index = at < 0 ? bytes.length + at : at;
  bytes[index] ^= 0x01;
  return base64Of(bytes);
}

/* Write one exact byte, where flipping a bit cannot reach the value the
 * check needs - a version byte set to a *different valid* version, or a
 * recipient count set to zero. */
function setByte(base64, at, value) {
  const bytes = bytesOf(base64);
  bytes[at] = value;
  return base64Of(bytes);
}

/*
 * Offsets into a version 2 blob, spelled out here rather than imported
 * from the module under test. A test that asks the implementation where
 * its own fields are cannot notice the implementation moving them,
 * which is the whole failure the committed fixtures exist to catch.
 * apps/web/crypto.js states the layout these come from.
 */
const V2 = {
  version: 0,
  count: 1,
  blocks: 2,
  block: 125,
  point: 0,
  wrapNonce: 65,
  wrappedKey: 77,
};

/* Where the content nonce starts in a blob carrying `count` blocks. */
const contentNonceAt = (count) => V2.blocks + V2.block * count;

/* A byte inside recipient block `index`, `offset` into that block. */
const blockByteAt = (index, offset) =>
  V2.blocks + V2.block * index + offset;

let failures = 0;
const results = [];

/*
 * Asserted at the end, the way dev/check_budget.test.py and its
 * siblings do it. Everything below is a top-level `await` in a file
 * that reports on what it ran, so a row that is deleted, commented out
 * or moved behind an early return leaves a suite that still prints
 * "all checks passed" - armed-looking and not armed, which this
 * repository holds to be worse than no check at all. Adding a row here
 * raises this number in the same diff.
 */
const EXPECTED = 63;

async function check(label, fn) {
  let ok = false;
  let note = "";
  try {
    ok = (await fn()) === true;
    if (!ok) note = "returned false";
  } catch (error) {
    note = "threw: " + (error && error.message ? error.message : error);
  }
  if (!ok) failures++;
  results.push([ok, label, note]);
}

/* The failure paths matter as much as the happy one: a decrypt that
 * quietly returns garbage instead of throwing is a corrupt export nobody
 * notices. Each of these must throw, and say something a person can act
 * on. */
async function mustReject(label, fn, fragment) {
  let note = "did not throw";
  let ok = false;
  try {
    await fn();
  } catch (error) {
    const message = String(error && error.message);
    ok = message.toLowerCase().includes(fragment.toLowerCase());
    note = ok ? "" : 'threw, but not about "' + fragment + '": ' + message;
  }
  if (!ok) failures++;
  results.push([ok, label, note]);
}

// ---------------------------------------------------------------------
// The shape of the export itself
// ---------------------------------------------------------------------

await check("the exported object is frozen", () =>
  // submit.html and admin.html both load this file and both hold
  // plaintext. An unfrozen export lets anything later on the page
  // replace `encrypt` with a passthrough, or hand admin's imported
  // private key to a substituted `decrypt`, and every round trip below
  // still passes because they all go through whatever is installed.
  // AGENTS.md, "Code standards", is where the rule lives.
  Object.isFrozen(globalThis.BinderCrypto));

// ---------------------------------------------------------------------
// The format, as already stored
// ---------------------------------------------------------------------

await check("a fixture from version 1 still decrypts", async () =>
  same(await decrypt(FIXTURE.blob, keyFile), FIXTURE.record));

await check("the fixture's unicode survives byte for byte", async () => {
  const out = await decrypt(FIXTURE.blob, keyFile);
  return out.note === FIXTURE.record.note;
});

// ---------------------------------------------------------------------
// The two-recipient format, as already stored
//
// Version 2 seals one record to two keys at once. Both of the next two
// checks read the *same* frozen bytes, and that is the point: a change
// that opens the row for the keyholder while quietly locking the member
// out passes every round trip below, because a round trip re-encrypts
// with the same broken code. Only a blob nobody can regenerate notices.
// ---------------------------------------------------------------------

await check("a fixture from version 2 decrypts for the keyholder", async () =>
  same(await decrypt(FIXTURE2.blob, keyFile), FIXTURE2.record));

await check("the same version 2 fixture decrypts for the member", async () =>
  same(await decrypt(FIXTURE2.blob, memberKeyFile), FIXTURE2.record));

await check("the version 2 fixture's unicode survives byte for byte",
  async () => {
    const out = await decrypt(FIXTURE2.blob, memberKeyFile);
    return out.note === FIXTURE2.record.note;
  });

await check("the version 2 fixture says it is version 2", async () =>
  bytesOf(FIXTURE2.blob)[V2.version] === 2 &&
  bytesOf(FIXTURE2.blob)[V2.count] === 2);

// ---------------------------------------------------------------------
// A fresh submission
// ---------------------------------------------------------------------

await check("a fresh record round-trips", async () => {
  const blob = await encrypt(FIXTURE.record, keyFile.publicKey);
  return same(await decrypt(blob, keyFile), FIXTURE.record);
});

await check("the blob is base64 the Worker accepts", async () => {
  const blob = await encrypt(FIXTURE.record, keyFile.publicKey);
  return WORKER_BASE64.test(blob) && blob.length < 16 * 1024;
});

await check("the same record twice gives two different blobs", async () => {
  // A fresh ephemeral key and nonce per submission. Were these equal,
  // the database would show which rows are repeat submissions of the
  // same values - which is exactly what encrypting is meant to hide.
  const a = await encrypt(FIXTURE.record, keyFile.publicKey);
  const b = await encrypt(FIXTURE.record, keyFile.publicKey);
  return a !== b;
});

await check("an empty record round-trips", async () =>
  same(await decrypt(await encrypt({}, keyFile.publicKey), keyFile), {}));

await check("a long record round-trips", async () => {
  // Well past anything the form can produce, and still inside the
  // Worker's 16 KB cap.
  const record = { ...FIXTURE.record, note: "x".repeat(4000) };
  return same(await decrypt(await encrypt(record, keyFile.publicKey), keyFile),
    record);
});

// ---------------------------------------------------------------------
// A fresh two-recipient submission
// ---------------------------------------------------------------------

await check("encryptTo emits format version 2", async () => {
  const blob = await encryptTo(FIXTURE.record,
    [keyFile.publicKey, memberKeyFile.publicKey]);
  return bytesOf(blob)[V2.version] === 2;
});

await check("encrypt still emits format version 1", async () => {
  // The submit path calls `encrypt` and will keep calling it until the
  // slice that switches pages over. A change here is a change to what
  // every live row looks like, so it is asserted rather than assumed.
  const blob = await encrypt(FIXTURE.record, keyFile.publicKey);
  return bytesOf(blob)[V2.version] === 1;
});

await check("a two-recipient record round-trips for both keys", async () => {
  const blob = await encryptTo(FIXTURE.record,
    [keyFile.publicKey, memberKeyFile.publicKey]);
  return same(await decrypt(blob, keyFile), FIXTURE.record) &&
    same(await decrypt(blob, memberKeyFile), FIXTURE.record);
});

await check("recipient order does not decide who can read", async () => {
  // A reader tries every block, so neither position is privileged.
  // Were the first block the only one consulted, the member would read
  // one ordering and the keyholder the other - and the export tool and
  // the member's own page pass different orderings.
  const blob = await encryptTo(FIXTURE.record,
    [memberKeyFile.publicKey, keyFile.publicKey]);
  return same(await decrypt(blob, keyFile), FIXTURE.record) &&
    same(await decrypt(blob, memberKeyFile), FIXTURE.record);
});

await check("a one-recipient version 2 record round-trips", async () =>
  same(await decrypt(await encryptTo(FIXTURE.record, [keyFile.publicKey]),
    keyFile), FIXTURE.record));

await check("a bare public key is accepted as one recipient", async () =>
  // The fallback slice 4 needs: no member key, so the page seals to the
  // keyholder alone rather than refusing to submit.
  same(await decrypt(await encryptTo(FIXTURE.record, keyFile.publicKey),
    keyFile), FIXTURE.record));

await check("the version 2 blob is base64 the Worker accepts", async () => {
  const blob = await encryptTo(FIXTURE.record,
    [keyFile.publicKey, memberKeyFile.publicKey]);
  return WORKER_BASE64.test(blob) && blob.length < 16 * 1024;
});

await check("the same record twice gives two different version 2 blobs",
  async () => {
    // Fresh ephemeral keys, a fresh content key and fresh nonces per
    // submission. Were these equal the database would show which rows
    // repeat which values, which is what encrypting is meant to hide.
    const a = await encryptTo(FIXTURE.record,
      [keyFile.publicKey, memberKeyFile.publicKey]);
    const b = await encryptTo(FIXTURE.record,
      [keyFile.publicKey, memberKeyFile.publicKey]);
    return a !== b;
  });

await check("an empty record round-trips through version 2", async () =>
  same(await decrypt(await encryptTo({},
    [keyFile.publicKey, memberKeyFile.publicKey]), memberKeyFile), {}));

await check("a long record round-trips through version 2", async () => {
  const record = { ...FIXTURE.record, note: "x".repeat(4000) };
  const blob = await encryptTo(record,
    [keyFile.publicKey, memberKeyFile.publicKey]);
  return same(await decrypt(blob, keyFile), record) &&
    same(await decrypt(blob, memberKeyFile), record);
});

await check("an imported private key decrypts many version 2 rows",
  async () => {
    // admin.html imports once and loops. The import is non-extractable,
    // so this is also the check that the version 2 reader never needs
    // its own public half - if it did, this path could not exist and
    // the whole page would have to hold an exportable private key.
    const key = await importPrivateKey(keyFile);
    const blobs = await Promise.all([1, 2, 3].map((n) =>
      encryptTo({ n: n }, [keyFile.publicKey, memberKeyFile.publicKey])));
    const out = await Promise.all(blobs.map((b) => decrypt(b, key)));
    return same(out, [{ n: 1 }, { n: 2 }, { n: 3 }]);
  });

await check("an imported public key works as a recipient", async () => {
  const key = await importPublicKey(memberKeyFile.publicKey);
  const blob = await encryptTo({ ok: true }, [keyFile.publicKey, key]);
  return same(await decrypt(blob, memberKeyFile), { ok: true });
});

await check("each recipient block carries its own ephemeral point",
  async () => {
    // One ephemeral pair shared across the row would work and would be
    // invisible to every other check here - both blocks would still
    // open, because two recipients give two shared secrets either way.
    // It is pinned because the format's promises rest on it: a block is
    // derivable from its own bytes, which is what lets a later re-seal
    // mint one block for a new device without touching the others.
    const bytes = bytesOf(await encryptTo(FIXTURE.record,
      [keyFile.publicKey, memberKeyFile.publicKey]));
    const point = (index) => base64Of(bytes.slice(
      blockByteAt(index, V2.point),
      blockByteAt(index, V2.point) + 65));
    return point(0) !== point(1);
  });

await check("writing a row draws a fresh content key and a nonce per block",
  async () => {
    // The one property of this format that leaves no trace in the blob.
    // A content key that stopped being random - a fixed buffer, a reused
    // one - passes every round trip, passes the frozen fixture (which
    // carries its own key inside it), and hands anyone who recovers one
    // row's key every other row. Counting what the writer asks the
    // CSPRNG for is the only way to see it from outside, so the spy is
    // here rather than a hook in a file that ships verbatim.
    const real = globalThis.crypto;
    const asked = [];
    const spy = {
      subtle: real.subtle,
      getRandomValues: (array) => {
        asked.push(array.length);
        return real.getRandomValues(array);
      },
    };
    const swap = (value) => Object.defineProperty(globalThis, "crypto",
      { value: value, configurable: true, writable: true });

    swap(spy);
    try {
      await encryptTo(FIXTURE.record,
        [keyFile.publicKey, memberKeyFile.publicKey]);
    } finally {
      swap(real);
    }

    const drawn = (size) => asked.filter((n) => n === size).length;
    // One 32-byte content key, and one 12-byte nonce for each of the two
    // wraps plus one for the body.
    return drawn(32) === 1 && drawn(12) === 3 && asked.length === 4;
  });

await check("a one-recipient row draws one wrap nonce fewer", async () => {
  const real = globalThis.crypto;
  const asked = [];
  const swap = (value) => Object.defineProperty(globalThis, "crypto",
    { value: value, configurable: true, writable: true });

  swap({
    subtle: real.subtle,
    getRandomValues: (array) => {
      asked.push(array.length);
      return real.getRandomValues(array);
    },
  });
  try {
    await encryptTo(FIXTURE.record, [keyFile.publicKey]);
  } finally {
    swap(real);
  }
  return asked.filter((n) => n === 32).length === 1 &&
    asked.filter((n) => n === 12).length === 2;
});

await check("a version 2 row grows by one block per recipient", async () => {
  // The layout is fixed-size on purpose: no length fields means no
  // length field to get wrong, and a reader can check the blob's length
  // against its recipient count before parsing anything.
  const one = bytesOf(await encryptTo({}, [keyFile.publicKey])).length;
  const two = bytesOf(await encryptTo({},
    [keyFile.publicKey, memberKeyFile.publicKey])).length;
  return two - one === V2.block;
});

// ---------------------------------------------------------------------
// How the key may be handed over
// ---------------------------------------------------------------------

await check("a bare JWK works as well as the envelope", async () => {
  const blob = await encrypt(FIXTURE.record, keyFile.publicKey);
  return same(await decrypt(blob, keyFile.privateKey), FIXTURE.record);
});

await check("the key file as pasted text works", async () => {
  const blob = await encrypt(FIXTURE.record, keyFile.publicKey);
  return same(await decrypt(blob, JSON.stringify(keyFile)), FIXTURE.record);
});

await check("an imported key decrypts many rows", async () => {
  // admin.html imports once and loops; this is that path.
  const key = await importPrivateKey(keyFile);
  const blobs = await Promise.all([1, 2, 3].map((n) =>
    encrypt({ n: n }, keyFile.publicKey)));
  const out = await Promise.all(blobs.map((b) => decrypt(b, key)));
  return same(out, [{ n: 1 }, { n: 2 }, { n: 3 }]);
});

await check("an imported public key encrypts", async () => {
  const key = await importPublicKey(keyFile.publicKey);
  return same(await decrypt(await encrypt({ ok: true }, key), keyFile),
    { ok: true });
});

// ---------------------------------------------------------------------
// Everything that must fail
// ---------------------------------------------------------------------

async function freshKeypair() {
  const pair = await crypto.subtle.generateKey(
    { name: "ECDH", namedCurve: "P-256" }, true, ["deriveBits"]);
  return {
    publicKey: base64Of(new Uint8Array(
      await crypto.subtle.exportKey("raw", pair.publicKey))),
    privateKey: await crypto.subtle.exportKey("jwk", pair.privateKey),
  };
}

const other = await freshKeypair();

await mustReject("another key cannot open a row",
  () => decrypt(FIXTURE.blob, other.privateKey), "different key");

await mustReject("a flipped bit in the ciphertext is caught",
  () => decrypt(tamper(FIXTURE.blob, -1), keyFile), "altered");

await mustReject("a flipped bit in the nonce is caught",
  // The nonce is authenticated as additional data, so editing it in the
  // database fails the tag rather than producing different plaintext.
  () => decrypt(tamper(FIXTURE.blob, 70), keyFile), "altered");

await mustReject("a flipped bit in the ephemeral key is caught",
  // Lands off the curve, so the browser rejects the point itself before
  // any derivation happens.
  () => decrypt(tamper(FIXTURE.blob, 20), keyFile), "corrupt");

await mustReject("an unknown format version is refused by name",
  () => decrypt(tamper(FIXTURE.blob, 0), keyFile), "version");

await mustReject("a truncated row is refused",
  () => decrypt(FIXTURE.blob.slice(0, 40), keyFile), "truncated");

await mustReject("something that is not base64 is refused",
  () => decrypt("not base64 at all !!", keyFile), "base64");

await mustReject("the public half is not accepted as the private one",
  () => decrypt(FIXTURE.blob, { ...keyFile.privateKey, d: undefined }),
  "public half");

await mustReject("a key for another curve is refused",
  () => decrypt(FIXTURE.blob, { ...keyFile.privateKey, crv: "P-384" }),
  "P-256");

await mustReject("a key file contradicting itself is refused",
  // Two halves of different keypairs filed together. Without this check
  // the symptom is "cannot decrypt" on every row, which looks the same
  // as holding the wrong key entirely.
  () => decrypt(FIXTURE.blob, { ...keyFile, publicKey: other.publicKey }),
  "contradicts itself");

await mustReject("a mangled public key is refused before encrypting",
  () => encrypt(FIXTURE.record, keyFile.publicKey.slice(0, 40)),
  "uncompressed P-256 point");

await mustReject("something that is not a key file is refused",
  () => decrypt(FIXTURE.blob, "hunter2"), "not the key file");

// ---------------------------------------------------------------------
// Everything that must fail, version 2
//
// Every byte region of the frozen two-recipient blob gets a flipped
// bit. A version 2 row has three regions version 1 does not - the
// recipient count, the wrap nonces and the wrapped content keys - and
// each is a place a change could be quietly wrong for one recipient
// while the other still reads fine.
// ---------------------------------------------------------------------

await mustReject("a third key opens no block of a version 2 row",
  // The refusal a non-recipient must get: clean, named, and saying
  // nothing about which block was tried or how far it got.
  () => decrypt(FIXTURE2.blob, other.privateKey), "recipient blocks");

await mustReject("a flipped bit in the version 2 ciphertext is caught",
  () => decrypt(tamper(FIXTURE2.blob, -1), keyFile), "altered");

await mustReject("a flipped bit in the content nonce is caught",
  // Authenticated as part of the header, so editing it in the database
  // fails the tag rather than producing different plaintext.
  () => decrypt(tamper(FIXTURE2.blob, contentNonceAt(2)), keyFile),
  "altered");

await mustReject("a flipped bit in the recipient count is caught",
  // The count is sealed into every block's own additional data, so a
  // row edited to claim a different number of recipients unwraps
  // nothing - it fails before the body's tag ever gets a say.
  () => decrypt(tamper(FIXTURE2.blob, V2.count), keyFile),
  "recipient blocks");

// Both of these name the bounds themselves rather than the word
// "recipient". Deleting the bounds check leaves a row claiming zero
// recipients falling through to "no block opened" and a row claiming
// nine falling through to "too short" - both refusals, both containing
// the word, and neither one this check. The mutation is what found it.
await mustReject("a version 2 row claiming no recipients is refused",
  () => decrypt(setByte(FIXTURE2.blob, V2.count, 0), keyFile),
  "between 1 and");

await mustReject("a version 2 row claiming more recipients than the format "
  + "carries is refused",
  () => decrypt(setByte(FIXTURE2.blob, V2.count, 9), keyFile),
  "between 1 and");

await mustReject("a flipped bit in the keyholder's ephemeral point is caught",
  // Lands off the curve, so that block cannot be tried at all. The
  // keyholder's own block is the one damaged, so nothing opens for them.
  () => decrypt(tamper(FIXTURE2.blob, blockByteAt(0, V2.point + 20)), keyFile),
  "recipient blocks");

await mustReject("a flipped bit in the keyholder's wrap nonce is caught",
  () => decrypt(tamper(FIXTURE2.blob, blockByteAt(0, V2.wrapNonce)), keyFile),
  "recipient blocks");

await mustReject("a flipped bit in the keyholder's wrapped key is caught",
  () => decrypt(tamper(FIXTURE2.blob, blockByteAt(0, V2.wrappedKey)), keyFile),
  "recipient blocks");

await mustReject("damage to the member's block also stops the keyholder",
  // The whole header is the body's additional data, so a block a reader
  // never needed is still a block they cannot have altered. Without
  // this, a row could be edited to strip a recipient and still open.
  () => decrypt(tamper(FIXTURE2.blob, blockByteAt(1, V2.wrappedKey)), keyFile),
  "altered");

await mustReject("a version 2 row read as version 1 is refused",
  // What a decoder that switched on nothing would do. Byte 1 of a
  // version 2 row is the recipient count, so version 1's reader takes a
  // point that starts one byte early and rejects it as off-curve.
  () => decrypt(setByte(FIXTURE2.blob, V2.version, 1), keyFile), "corrupt");

await mustReject("a version this file does not know is refused by name",
  () => decrypt(setByte(FIXTURE2.blob, V2.version, 3), keyFile), "version 3");

await mustReject("a truncated version 2 row is refused",
  () => decrypt(FIXTURE2.blob.slice(0, 120), keyFile), "truncated");

await mustReject("a version 2 row too short to hold its own count is refused",
  // "Ag==" is the version byte and nothing else, so byte 1 does not
  // exist. Every bound in the reader compares false against undefined,
  // which sent this row all the way through to "no block opened" - a
  // damaged row reported to whoever is exporting as the wrong key.
  () => decrypt("Ag==", keyFile), "truncated");

await mustReject("a version 2 row one byte short of a block is refused",
  () => decrypt(base64Of(bytesOf(FIXTURE2.blob).slice(0, 154)), keyFile),
  "truncated");

await mustReject("a version 2 row with no recipients cannot be written",
  () => encryptTo(FIXTURE.record, []), "at least one");

await mustReject("more recipients than the format carries cannot be written",
  // Five DISTINCT keys. A list padded with repeats would be refused by
  // the duplicate guard instead, and this check would report itself as
  // armed while testing the other rule - which is what it did until a
  // mutation removed the ceiling and it kept passing.
  async () => encryptTo(FIXTURE.record, [
    keyFile.publicKey, memberKeyFile.publicKey, other.publicKey,
    (await freshKeypair()).publicKey, (await freshKeypair()).publicKey]),
  "at most");

await mustReject("the same recipient twice cannot be written",
  // The shape of the bug this catches: the page seals to the keyholder
  // twice because the member key it fetched came back as the config
  // key. The row would look dual-sealed and open for nobody new, and
  // nothing downstream could tell.
  () => encryptTo(FIXTURE.record, [keyFile.publicKey, keyFile.publicKey]),
  "same recipient");

await mustReject("a mangled recipient is refused before encrypting",
  () => encryptTo(FIXTURE.record,
    [keyFile.publicKey, memberKeyFile.publicKey.slice(0, 40)]),
  "uncompressed P-256 point");

// ---------------------------------------------------------------------

for (const [ok, label, note] of results) {
  console.log(`${ok ? "pass" : "FAIL"}  ${label.padEnd(50)} ${note}`);
}

if (failures) {
  console.log(`\n${failures} FAILURE(S)`);
  process.exit(1);
}
if (results.length !== EXPECTED) {
  console.log(`\nran ${results.length} checks, expected ${EXPECTED} - a ` +
    "check stopped running, or one was added without updating EXPECTED");
  process.exit(1);
}
console.log(`\nall checks passed - ${results.length} checks`);
process.exit(0);
