/*
 * Round-trip checks for apps/web/crypto.js.
 *
 *     node dev/crypto.test.mjs
 *
 * This is the test the build order puts before the form. A form that
 * silently produces undecryptable ciphertext is indistinguishable from a
 * working one until export day, and by then the data is gone - so the
 * proof that encrypt and decrypt agree has to exist before anything is
 * collected, not after.
 *
 * Node's WebCrypto is the same specification the browser implements, so
 * the real file runs here unmodified. It is loaded through a data: URL,
 * the way dev/worker.test.mjs loads the Worker: crypto.js is a classic
 * script that assigns to globalThis, this repository has no package.json,
 * and importing the real bytes is what makes this a test of what ships
 * rather than of a copy.
 *
 * Two kinds of check, and the second is the one worth having:
 *
 *   - a fresh keypair encrypts and decrypts, and the failures fail.
 *   - a ciphertext committed months ago still opens. Rows outlive the
 *     code that wrote them. Every other test here passes just as happily
 *     after a change that quietly alters the format - a new label, a
 *     different salt, a reordered header - and that change would leave
 *     the live database unreadable with no error anywhere. The fixture
 *     below is the only thing that notices.
 */
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const HERE = (p) => fileURLToPath(new URL(p, import.meta.url));

const src = await readFile(HERE("../apps/web/crypto.js"), "utf8");
await import("data:text/javascript," + encodeURIComponent(src));
const { encrypt, decrypt, importPrivateKey, importPublicKey } =
  globalThis.BinderCrypto;

/*
 * The test keypair. Throwaway, committed on purpose: it protects
 * nothing and opens nothing real. The key the portal actually uses was
 * generated by the keyholder on their own machine and has never been in
 * this repository - see DESIGN.md, "Key custody".
 */
const keyFile = JSON.parse(await readFile(HERE("test-key.json"), "utf8"));

/*
 * A ciphertext written by version 1 of the format, against the key
 * above, and the record it must come back as. Kept in its own file
 * because crypto-browser-check.html reads the same one - the same
 * assertion made twice against two copies of the fixture would be two
 * things to keep in step, and the copy that drifted would be the one
 * still passing.
 *
 * Do not regenerate it to make a failing test pass. See dev/README.md.
 */
const FIXTURE = JSON.parse(await readFile(HERE("fixture.json"), "utf8"));

/* What server/worker.js will accept: standard base64, nothing else. */
const WORKER_BASE64 = /^[A-Za-z0-9+/]+={0,2}$/;

const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);

function bytesOf(base64) {
  const binary = atob(base64);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
  return out;
}

function base64Of(bytes) {
  let binary = "";
  for (const b of bytes) binary += String.fromCharCode(b);
  return btoa(binary);
}

/* Flip one bit at `at`, counting from the end when negative. */
function tamper(base64, at) {
  const bytes = bytesOf(base64);
  const index = at < 0 ? bytes.length + at : at;
  bytes[index] ^= 0x01;
  return base64Of(bytes);
}

let failures = 0;
const results = [];

async function check(label, fn) {
  let ok = false;
  let note = "";
  try {
    ok = (await fn()) === true;
    if (!ok) note = "returned false";
  } catch (error) {
    note = "threw: " + (error && error.message ? error.message : error);
  }
  if (!ok) failures++;
  results.push([ok, label, note]);
}

/* The failure paths matter as much as the happy one: a decrypt that
 * quietly returns garbage instead of throwing is a corrupt export nobody
 * notices. Each of these must throw, and say something a person can act
 * on. */
async function mustReject(label, fn, fragment) {
  let note = "did not throw";
  let ok = false;
  try {
    await fn();
  } catch (error) {
    const message = String(error && error.message);
    ok = message.toLowerCase().includes(fragment.toLowerCase());
    note = ok ? "" : 'threw, but not about "' + fragment + '": ' + message;
  }
  if (!ok) failures++;
  results.push([ok, label, note]);
}

// ---------------------------------------------------------------------
// The format, as already stored
// ---------------------------------------------------------------------

await check("a fixture from version 1 still decrypts", async () =>
  same(await decrypt(FIXTURE.blob, keyFile), FIXTURE.record));

await check("the fixture's unicode survives byte for byte", async () => {
  const out = await decrypt(FIXTURE.blob, keyFile);
  return out.note === FIXTURE.record.note;
});

// ---------------------------------------------------------------------
// A fresh submission
// ---------------------------------------------------------------------

await check("a fresh record round-trips", async () => {
  const blob = await encrypt(FIXTURE.record, keyFile.publicKey);
  return same(await decrypt(blob, keyFile), FIXTURE.record);
});

await check("the blob is base64 the Worker accepts", async () => {
  const blob = await encrypt(FIXTURE.record, keyFile.publicKey);
  return WORKER_BASE64.test(blob) && blob.length < 16 * 1024;
});

await check("the same record twice gives two different blobs", async () => {
  // A fresh ephemeral key and nonce per submission. Were these equal,
  // the database would show which rows are repeat submissions of the
  // same values - which is exactly what encrypting is meant to hide.
  const a = await encrypt(FIXTURE.record, keyFile.publicKey);
  const b = await encrypt(FIXTURE.record, keyFile.publicKey);
  return a !== b;
});

await check("an empty record round-trips", async () =>
  same(await decrypt(await encrypt({}, keyFile.publicKey), keyFile), {}));

await check("a long record round-trips", async () => {
  // Well past anything the form can produce, and still inside the
  // Worker's 16 KB cap.
  const record = { ...FIXTURE.record, note: "x".repeat(4000) };
  return same(await decrypt(await encrypt(record, keyFile.publicKey), keyFile),
    record);
});

// ---------------------------------------------------------------------
// How the key may be handed over
// ---------------------------------------------------------------------

await check("a bare JWK works as well as the envelope", async () => {
  const blob = await encrypt(FIXTURE.record, keyFile.publicKey);
  return same(await decrypt(blob, keyFile.privateKey), FIXTURE.record);
});

await check("the key file as pasted text works", async () => {
  const blob = await encrypt(FIXTURE.record, keyFile.publicKey);
  return same(await decrypt(blob, JSON.stringify(keyFile)), FIXTURE.record);
});

await check("an imported key decrypts many rows", async () => {
  // admin.html imports once and loops; this is that path.
  const key = await importPrivateKey(keyFile);
  const blobs = await Promise.all([1, 2, 3].map((n) =>
    encrypt({ n: n }, keyFile.publicKey)));
  const out = await Promise.all(blobs.map((b) => decrypt(b, key)));
  return same(out, [{ n: 1 }, { n: 2 }, { n: 3 }]);
});

await check("an imported public key encrypts", async () => {
  const key = await importPublicKey(keyFile.publicKey);
  return same(await decrypt(await encrypt({ ok: true }, key), keyFile),
    { ok: true });
});

// ---------------------------------------------------------------------
// Everything that must fail
// ---------------------------------------------------------------------

const other = await (async () => {
  const pair = await crypto.subtle.generateKey(
    { name: "ECDH", namedCurve: "P-256" }, true, ["deriveBits"]);
  return {
    publicKey: base64Of(new Uint8Array(
      await crypto.subtle.exportKey("raw", pair.publicKey))),
    privateKey: await crypto.subtle.exportKey("jwk", pair.privateKey),
  };
})();

await mustReject("another key cannot open a row",
  () => decrypt(FIXTURE.blob, other.privateKey), "different key");

await mustReject("a flipped bit in the ciphertext is caught",
  () => decrypt(tamper(FIXTURE.blob, -1), keyFile), "altered");

await mustReject("a flipped bit in the nonce is caught",
  // The nonce is authenticated as additional data, so editing it in the
  // database fails the tag rather than producing different plaintext.
  () => decrypt(tamper(FIXTURE.blob, 70), keyFile), "altered");

await mustReject("a flipped bit in the ephemeral key is caught",
  // Lands off the curve, so the browser rejects the point itself before
  // any derivation happens.
  () => decrypt(tamper(FIXTURE.blob, 20), keyFile), "corrupt");

await mustReject("an unknown format version is refused by name",
  () => decrypt(tamper(FIXTURE.blob, 0), keyFile), "version");

await mustReject("a truncated row is refused",
  () => decrypt(FIXTURE.blob.slice(0, 40), keyFile), "truncated");

await mustReject("something that is not base64 is refused",
  () => decrypt("not base64 at all !!", keyFile), "base64");

await mustReject("the public half is not accepted as the private one",
  () => decrypt(FIXTURE.blob, { ...keyFile.privateKey, d: undefined }),
  "public half");

await mustReject("a key for another curve is refused",
  () => decrypt(FIXTURE.blob, { ...keyFile.privateKey, crv: "P-384" }),
  "P-256");

await mustReject("a key file contradicting itself is refused",
  // Two halves of different keypairs filed together. Without this check
  // the symptom is "cannot decrypt" on every row, which looks the same
  // as holding the wrong key entirely.
  () => decrypt(FIXTURE.blob, { ...keyFile, publicKey: other.publicKey }),
  "contradicts itself");

await mustReject("a mangled public key is refused before encrypting",
  () => encrypt(FIXTURE.record, keyFile.publicKey.slice(0, 40)),
  "uncompressed P-256 point");

await mustReject("something that is not a key file is refused",
  () => decrypt(FIXTURE.blob, "hunter2"), "not the key file");

// ---------------------------------------------------------------------

for (const [ok, label, note] of results) {
  console.log(`${ok ? "pass" : "FAIL"}  ${label.padEnd(50)} ${note}`);
}
console.log(failures ? `\n${failures} FAILURE(S)` : "\nall checks passed");
process.exit(failures ? 1 : 0);
